In [1]:
import numpy as np

In [12]:
kernel = np.array([], dtype='float32')
out_channels = 32

for i in range(out_channels):
    kernel = np.append(kernel, [[-1, -1, -1], [-1, i, -1], [-1, -1, -1]])

kernel = kernel.reshape((1, out_channels, 3, 3))

In [13]:
print(kernel)

[[[[-1. -1. -1.]
   [-1.  0. -1.]
   [-1. -1. -1.]]

  [[-1. -1. -1.]
   [-1.  1. -1.]
   [-1. -1. -1.]]

  [[-1. -1. -1.]
   [-1.  2. -1.]
   [-1. -1. -1.]]

  [[-1. -1. -1.]
   [-1.  3. -1.]
   [-1. -1. -1.]]

  [[-1. -1. -1.]
   [-1.  4. -1.]
   [-1. -1. -1.]]

  [[-1. -1. -1.]
   [-1.  5. -1.]
   [-1. -1. -1.]]

  [[-1. -1. -1.]
   [-1.  6. -1.]
   [-1. -1. -1.]]

  [[-1. -1. -1.]
   [-1.  7. -1.]
   [-1. -1. -1.]]

  [[-1. -1. -1.]
   [-1.  8. -1.]
   [-1. -1. -1.]]

  [[-1. -1. -1.]
   [-1.  9. -1.]
   [-1. -1. -1.]]

  [[-1. -1. -1.]
   [-1. 10. -1.]
   [-1. -1. -1.]]

  [[-1. -1. -1.]
   [-1. 11. -1.]
   [-1. -1. -1.]]

  [[-1. -1. -1.]
   [-1. 12. -1.]
   [-1. -1. -1.]]

  [[-1. -1. -1.]
   [-1. 13. -1.]
   [-1. -1. -1.]]

  [[-1. -1. -1.]
   [-1. 14. -1.]
   [-1. -1. -1.]]

  [[-1. -1. -1.]
   [-1. 15. -1.]
   [-1. -1. -1.]]

  [[-1. -1. -1.]
   [-1. 16. -1.]
   [-1. -1. -1.]]

  [[-1. -1. -1.]
   [-1. 17. -1.]
   [-1. -1. -1.]]

  [[-1. -1. -1.]
   [-1. 18. -1.]
   [-1. -1. 